jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        brew update
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/#{tap}"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        brew test-bot
      displayName: Run brew test-bot
