name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Run brew test-bot on macOS
    runs-on: macOS-latest
    steps:
      - name: test-bot
        uses: actions/checkout@v1
        run: .github/ci.sh

