name: Dispatch rebottle

on:
  workflow_dispatch:
    inputs:
      formula:
        description: Formula name
        required: true
      issue:
        description: Issue number, where comment on failure would be posted
        required: false
      upload:
        description: "Whether to upload built bottles or not (default: false)"
        required: false

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  bottle:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_FORCE_VENDOR_RUBY: 1
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: ${{github.event.inputs.formula}}
        id: print_details
        run: |
          echo sender=${{github.event.sender.login}}
          echo formula=${{github.event.inputs.formula}}
          echo issue=${{github.event.inputs.issue}}
          echo upload=${{github.event.inputs.upload}}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae --only-json-tab --skip-recursive-dependents --root-url="https://ghcr.io/v2/jonchang/biology" ${{github.event.inputs.formula}}

      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'

  upload:
    runs-on: ubuntu-latest
    needs: bottle
    if: github.event.inputs.upload
    env:
      HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
    steps:
      - name: ${{github.event.inputs.formula}}
        id: print_details
        run: |
          echo sender=${{github.event.sender.login}}
          echo formula=${{github.event.inputs.formula}}
          echo version=${{github.event.inputs.macos}}
          echo issue=${{github.event.inputs.issue}}
          echo upload=${{github.event.inputs.upload}}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Download bottles from GitHub Actions
        uses: actions/download-artifact@main
        with:
          name: bottles
          path: ~/bottles/

      - name: Setup git
        uses: Homebrew/actions/git-user-config@master

      - name: Upload bottles to GitHub Packages
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_GITHUB_PACKAGES_USER: jonchang
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          cd ~/bottles
          brew pr-upload --debug --github-org=jonchang --root-url="https://ghcr.io/v2/jonchang/biology"

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: master
