name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled
jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Customize Homebrew
        run: |
          cd $(brew --repo)
          git remote add jonchang https://github.com/jonchang/brew
          git fetch jonchang
          git checkout third-party-packages

      - name: Pull bottles
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_GITHUB_PACKAGES_USER: jonchang
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          brew pr-pull --debug --autosquash --tap=$GITHUB_REPOSITORY --github-org=jonchang --root-url="https://ghcr.io/v2/jonchang/biology" $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: master

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin $BRANCH
