name: CI

on:
  push:
    branches: master
  pull_request: []

jobs:
  tap_syntax:
    name: Check tap syntax
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up tap
        run: |
          set -e
          brew update
          REPO=$(brew --repo ${{github.repository}})
          mkdir -p "$REPO"
          rm -rf "$REPO"
          ln -s "$PWD" "$REPO"
      - name: Check syntax
        run: |
          brew test-bot --only-tap-syntax --tap=${{github.repository}}

  build-linux:
    needs: tap_syntax
    if: github.event_name == 'pull_request'
    name: Build Linux bottle
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Setup Homebrew
        run: |
          cd $(brew --repo)
          git stash
          git clean -d -f
      - name: Setup tap
        run: |
          mkdir -p "$(dirname $(brew --repo ${{github.repository}}))"
          cp -a "$GITHUB_WORKSPACE" "$(brew --repo ${{github.repository}})"
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{github.event.repository.owner.login}}/bottles-biology
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --root-url=$HOMEBREW_BINTRAY_URL --tap=jonchang/biology
      - name: Copy bottles
        if: always()
        run: |
          cp -a ~/bottles $RUNNER_TEMP/
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ${{runner.temp}}/bottles

  build-macos:
    needs: tap_syntax
    if: github.event_name == 'pull_request'
    name: Build macOS bottle
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Update Homebrew
        run: |
          rm -rf $(brew --repo homebrew/cask)
          rm -rf $(brew --repo homebrew/cask-versions)
          brew update-reset
          brew cask install xquartz
      - name: Setup tap
        run: |
          mkdir -p "$(dirname $(brew --repo ${{github.repository}}))"
          cp -a "$GITHUB_WORKSPACE" "$(brew --repo ${{github.repository}})"
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{github.event.repository.owner.login}}/bottles-biology
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --root-url=$HOMEBREW_BINTRAY_URL --tap=jonchang/biology
      - name: Copy bottles
        if: always()
        run: |
          cp -a ~/bottles $RUNNER_TEMP/
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ${{runner.temp}}/bottles

