name: CI

on:
  push:
    branches: master
  pull_request: []

jobs:
  tap_syntax:
    name: Check tap syntax
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up tap
        run: |
          set -e
          brew update
          REPO=$(brew --repo ${{github.repository}})
          mkdir -p "$REPO"
          rm -rf "$REPO"
          ln -s "$PWD" "$REPO"
      - name: Check syntax
        run: |
          brew test-bot --only-tap-syntax --tap=${{github.repository}}

  build-linux:
    needs: tap_syntax
    if: github.event_name == 'pull_request'
    name: Build Linux bottle
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Set up tap
        run: |
          REPO=$(brew --repo ${{github.repository}})
          mkdir -p "$REPO"
          rm -rf "$REPO"
          ln -s $GITHUB_WORKSPACE "$REPO"
      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup --tap=${{github.repository}}
      - name: Run brew test-bot --only-formulae
        env:
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{github.event.repository.owner.login}}/bottles-biology
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae --root-url=$HOMEBREW_BINTRAY_URL --tap=${{github.repository}}
      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
            cat ~/bottles/steps_output.txt
            rm ~/bottles/steps_output.txt
      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"
      - name: Move bottles
        if: always() && steps.bottles.outputs.count > 0
        run: mv ~/bottles $GITHUB_WORKSPACE
      - name: Upload bottles
        if: always() && steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles

  build-macos:
    needs: tap_syntax
    if: github.event_name == 'pull_request'
    name: Build macOS bottle
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Update Homebrew
        run: |
          rm -rf $(brew --repo homebrew/cask)
          rm -rf $(brew --repo homebrew/cask-versions)
          brew update-reset
          brew rm $(brew ls)
          brew cleanup
          brew cask install xquartz
      - name: Set up tap
        run: |
          REPO=$(brew --repo ${{github.repository}})
          mkdir -p "$REPO"
          rm -rf "$REPO"
          ln -s $GITHUB_WORKSPACE "$REPO"
      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup --tap=${{github.repository}}
      - name: Run brew test-bot --only-formulae
        env:
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{github.event.repository.owner.login}}/bottles-biology
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae --root-url=$HOMEBREW_BINTRAY_URL --tap=${{github.repository}}
      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
            cat ~/bottles/steps_output.txt
            rm ~/bottles/steps_output.txt
      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"
      - name: Move bottles
        if: always() && steps.bottles.outputs.count > 0
        run: mv ~/bottles $GITHUB_WORKSPACE
      - name: Upload bottles
        if: always() && steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
