name: Upload bottles.

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/*'

jobs:
  upload-bottles:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Determine associated pull request
        uses: actions/github-script@0.9.0
        id: pr
        with:
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              ...context.repo,
              commit_sha: context.payload.head_commit.id
            })
            console.log(prs.data.length + " prs")
            if (prs.data.length === 0) {
              throw "No pull requests are associated with this merge commit."
            }
            core.setOutput("number", prs.data[0].number.toString())
            core.setOutput("head_sha", prs.data[0].head.sha)

      - name: Download workflow artifacts
        uses: Homebrew/actions/download-artifact@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: tests.yml
          commit: ${{steps.pr.outputs.head_sha}}
          name: bottles
          path: bottles

      - name: Upload bottles
        env:
          HOMEBREW_BOTTLE_DOMAIN: https://dl.bintray.com/${{github.event.repository.owner.login}}
          HOMEBREW_BINTRAY_USER:  ${{github.event.repository.owner.login}}
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{github.event.repository.owner.login}}/bottles-biology
        run: |
          cd bottles
          brew test-bot --root-url=$HOMEBREW_BINTRAY_URL --bintray-org=$HOMEBREW_BINTRAY_USER --ci-upload --publish

      - name: Push bottle commit
        env:
          GIT_COMMITTER_NAME: ${{github.event.pusher.name}}
          GIT_COMMITTER_EMAIL: ${{github.event.pusher.email}}
        run: |
          cd $(brew --repo ${{github.repository}})
          git commit --amend --no-edit
          git show --pretty=fuller
          for try in $(seq 5); do
            git fetch
            git rebase origin/master
            if git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master; then
              break
            else
              sleep 3s
            fi
          done
